<?php

/**
 * BaseIncome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $amount
 * @property string $description
 * 
 * @method decimal getAmount()      Returns the current record's "amount" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method Income  setAmount()      Sets the current record's "amount" value
 * @method Income  setDescription() Sets the current record's "description" value
 * 
 * @package    finances
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIncome extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('income');
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('description', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}