<?php

/**
 * BaseIncome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property datetime $date_from
 * @property datetime $date_to
 * @property decimal $amount
 * @property string $name
 * 
 * @method datetime getDateFrom()  Returns the current record's "date_from" value
 * @method datetime getDateTo()    Returns the current record's "date_to" value
 * @method decimal  getAmount()    Returns the current record's "amount" value
 * @method string   getName()      Returns the current record's "name" value
 * @method Income   setDateFrom()  Sets the current record's "date_from" value
 * @method Income   setDateTo()    Sets the current record's "date_to" value
 * @method Income   setAmount()    Sets the current record's "amount" value
 * @method Income   setName()      Sets the current record's "name" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIncome extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('income');
        $this->hasColumn('date_from', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('date_to', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}