<?php

/**
 * BaseIncomeCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property IncomeCategory $Parent
 * @property Doctrine_Collection $Incomes
 * @property Doctrine_Collection $Children
 * 
 * @method IncomeCategory      getParent()   Returns the current record's "Parent" value
 * @method Doctrine_Collection getIncomes()  Returns the current record's "Incomes" collection
 * @method Doctrine_Collection getChildren() Returns the current record's "Children" collection
 * @method IncomeCategory      setParent()   Sets the current record's "Parent" value
 * @method IncomeCategory      setIncomes()  Sets the current record's "Incomes" collection
 * @method IncomeCategory      setChildren() Sets the current record's "Children" collection
 * 
 * @package    finances
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIncomeCategory extends Category
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IncomeCategory as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('Income as Incomes', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('IncomeCategory as Children', array(
             'local' => 'id',
             'foreign' => 'parent_id'));
    }
}