<?php

/**
 * BaseOutcomeCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property OutcomeCategory $Parent
 * @property Doctrine_Collection $Outcomes
 * @property Doctrine_Collection $Children
 * 
 * @method OutcomeCategory     getParent()   Returns the current record's "Parent" value
 * @method Doctrine_Collection getOutcomes() Returns the current record's "Outcomes" collection
 * @method Doctrine_Collection getChildren() Returns the current record's "Children" collection
 * @method OutcomeCategory     setParent()   Sets the current record's "Parent" value
 * @method OutcomeCategory     setOutcomes() Sets the current record's "Outcomes" collection
 * @method OutcomeCategory     setChildren() Sets the current record's "Children" collection
 * 
 * @package    finances
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOutcomeCategory extends Category
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OutcomeCategory as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('Outcome as Outcomes', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('OutcomeCategory as Children', array(
             'local' => 'id',
             'foreign' => 'parent_id'));
    }
}