generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Income
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          income
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   admin

    config:
      actions: ~
      fields:
        date_from:
          label: Od
        date_to:
          label: Do
        period:
          label: Okres
        amount:
          label: Kwota
        name:
          label: Opis
        created_at:
          label: Utworzono
        created_by:
          label: Utworzył
        creator:
          label: Utworzył(a)
      list:
        display: [ _amount, _period, creator ]
        title: Lista przychodów
        max_per_page: 50
        table_method: getIncomesBackendListQuery
      filter:
        display: [ created_by ]
      form:
        fields:
          amount:
            attributes: { size: 10 }
          name:
            attributes: { size: 50 }
      edit:
        title: Edytuj przychód
      new:
        title: Dodaj przychód
