generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Outcome
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          outcome
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   admin

    config:
      actions: ~
      fields:
        category_id:
          label: Kategoria
        Category:
          label: Kategoria
        comment:
          label: Komentarz
        comment:
          label: Komentarz
        amount:
          label: Kwota
        amount_range:
          label: Zakres kwot
        remember_date:
          label: Zapamiętaj datę
        created_at:
          label: Utworzono
        created_by:
          label: Utworzył(a)
        Creator:
          label: Utworzył(a)
      list:
        display: [ Category, _amount, Creator, _created_at ]
        title: Lista wydatków
        max_per_page: 20
        table_method: getOutcomesBackendListQuery
      filter:
        display: [ category_id, amount_range, created_by, created_at ]
      form:
        display: [ amount, category_id, created_by, created_at, remember_date, comment ]
        fields:
          amount:
            attributes: { size: 10 }
          comment:
            attributes: { size: 50 }
      edit:
        title: Edytuj wydatek
      new:
        title: Dodaj wydatek
