# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [ thickbox.css ]

  javascripts:    [ jquery-latest.pack.js, thickbox-compressed.js ]

  has_layout:     true
  layout:         layout
