<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    finances
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
  /**
   * Returns indented name.
   *
   * @return String - indented name
   */
  public function getIndentedName()
  {
    return ($this['parent_id'] ? '&nbsp;&nbsp;&nbsp;' : '').$this->getName();
  }

  /**
   * Returns total cash spent on a particular Category.
   *
   * @return Decimal
   */
  public function getCashTotalSum()
  {
    $sum = 0;
    foreach ($this->getOutcomes() as $outcome)
    {
      $sum += $outcome->getCashTotal();
    }
    return $sum;
  }
}
