<?php

/**
 * IncomeCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IncomeCategoryTable extends CategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object IncomeCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IncomeCategory');
    }
}