<?php

/**
 * IncomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IncomeTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object IncomeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Income');
  }

  /**
   * Returns query retrieving Income objects with related data. Method used in
   * symfony/doctrine admin backend module list.
   *
   * @return object Doctrine_Query
   */
  public static function getIncomesBackendListQuery()
  {
    return Doctrine_Query::create()
      ->from('Income i')
      ->leftJoin('i.Creator cr')
      ->orderBy('i.created_at DESC');
  }
}
