<?php

/**
 * OutcomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OutcomeTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object OutcomeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Outcome');
  }

  /**
   * Returns query retrieving Outcome objects with related data. Method used in
   * symfony/doctrine admin backend module list.
   *
   * @return object Doctrine_Query
   */
  public static function getOutcomesBackendListQuery()
  {
    return Doctrine_Query::create()
      ->from('Outcome o')
      ->leftJoin('o.Category ctg')
      ->leftJoin('o.Creator cr')
      ->orderBy('o.created_at DESC');
  }
}