<?php

/**
 * OutcomeCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OutcomeCategoryTable extends CategoryTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object OutcomeCategoryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('OutcomeCategory');
  }

  /**
   * Returns query retrieving all categories with outcomes. Used in Category Pie
   * chart.
   *
   * @param Array $chart - from/to
   * @return object Doctrine_Query
   */
  public function getAllCategoriesWithOutcomesQuery($chart)
  {
    $signable_clause = $chart['created_by'] ? "AND o.created_by = {$chart['created_by']}" : '';
    $clause = ($chart ? " ON c.id = o.category_id
      {$signable_clause} AND (o.created_at BETWEEN '{$chart['date_from']}' AND '{$chart['date_to']}')" : '');
    return self::createQuery('c')
      ->leftJoin('c.Outcomes o'.$clause)
      ->orderBy('c.name ASC');
  }
}
