<?php

/**
 * Outcome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    finances
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Outcome extends BaseOutcome
{
  /**
   * Returns true if the outcome was made today.
   *
   * @return Boolean
   */
  public function isToday()
  {
    return (date("Y-m-d") == substr($this->getCreatedAt(), 0, 10));
  }

  /**
   * Returns true if the outcome is expensive (cash amount the same or higher than
   * a constant given in application configuration).
   *
   * @return Boolean
   */
  public function isExpensive()
  {
    return ($this->getAmount() >= sfConfig::get('app_outcome_expensive'));
  }
}
